name: Generate RSS

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate feed.xml
        run: python generate_rss.py

      - name: Commit and push to gh-pages
        run: |
          git config --global user.name "Lambersart"
          git config --global user.email "ville@lambersart.fr"
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages
          cp feed.xml ./feed.xml
          git add feed.xml
          git commit -m "Update feed.xml" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GIT_AUTHOR_NAME: Lambersart
          GIT_AUTHOR_EMAIL: ville@lambersart.fr
          GIT_COMMITTER_NAME: Lambersart
          GIT_COMMITTER_EMAIL: ville@lambersart.fr
