name: Generate RSS

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate feed.xml
        run: python generate_rss.py

      - name: Push to separate repo
        run: |
          git clone https://x-access-token:${{ secrets.FEED_PUSH_TOKEN }}@github.com/Lambersart59130/lambersart-rss-feed.git out
          cd out
          git checkout --orphan gh-pages
          rm -rf .
          cp ../feed.xml .
          git config user.name "Lambersart"
          git config user.email "ville@lambersart.fr"
          git add feed.xml
          git commit -m "Update feed"
          git push -f origin gh-pages
